version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8090:8090"
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gpsolution
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"