INSERT INTO role(name) values ('USER');
INSERT INTO role(name) values ('ADMIN');
insert into factory_description(phone, position) values ('+375445333880','manager');
insert into factory_description(phone, position) values ('+375445333880','production manager');
insert into company_description (company, discount, info, phone) values (' ООО"Аливария"',10,'Пивоварня №1 в СНГ','+375445333880');
insert into relation_type(factory_description_id) values (1);
insert into relation_type(factory_description_id) values (2);
insert into relation_type(company_description_id) values (1);
insert into user_description(relation_type_id, role_id) VALUEs (1,2);
insert into user_description(relation_type_id, role_id) VALUEs (2,2);
insert into user_description(relation_type_id, role_id) VALUEs (3,1);
insert into users(email, full_name, user_description_id) values ('petya@email.com','Петя Петрович Пупкин',1);
insert into users(email, full_name, user_description_id) values ('dima@email.com','Дима Михайлович Андропов',2);
insert into users(email, full_name, user_description_id) values ('vasya@email.com','Пупкин Василий Иванович',3);
insert into auth_info_entity(login, password, users_id) values ('petya@email.com','$2y$10$hlEr2dDX5P/uB35dqySWMe2fLX5HdLTjOm4sUpkohMgEpiRLImRQS',1);
insert into auth_info_entity(login, password, users_id) values ('dima@email.com','$2y$10$VdERCAzwLEH7Pk5VTdQiwuDeL7vl8qL8TXR6UFEihxx4baGK.BFzy',2);
insert into auth_info_entity(login, password, users_id) values ('vasya@email.com','$2a$10$XSmc.fcrTETtBMyW6KaV4ugDeaUFXKFGtx38h36KOxtnFVtg9qMh6',3);
insert into product(category, name, prime_cost, type) values ('Тара для хранения','Бутылка',60,'0.5');
insert into product(category, name, prime_cost, type) values ('Фильтрация и сорбирование','Воздушный фильтр',40,'0.1');
insert into product(category, name, prime_cost, type) values ('Устройства для розлива','Кран',12000,'45-120');
